# install     pip3 install pre-commit
#             sudo apt install cppcheck
# run         pre-commit run -a
# update      pre-commit autoupdate

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-executables-have-shebangs
      - id: detect-private-key
      - id: mixed-line-ending
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-toml
      - id: fix-byte-order-marker

  - repo: https://github.com/codespell-project/codespell
    rev: "v2.2.5"
    hooks:
      - id: codespell

  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: 'v15.0.7'
    hooks:
      - id: clang-format
        #types_or: [c++, c]

  # cpp-check comes last! fails if uninstalled
  - repo: https://github.com/pocc/pre-commit-hooks
    rev: "v1.3.5"
    hooks:
      - id: cppcheck
        args:
          - "--enable=all"
          - "--std=c++11"
          - "--language=c++"
          - "--platform=unix32"
          - "--verbose"
          - "-q"
          - "--max-ctu-depth=10"
          - "--suppress=unusedFunction"
          - "--force"
          - "-I./src"
          - "--check-config"
